name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 3
    - name: Setup golang
      uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'
    - name: Run tests
      run: |
        cd ./golang
        go test -buildvcs=false ./... 
